let arr = [{
    'title': 'zapravdu_astrahan',
    'href': 'https://vk.com/zapravdu_astrahan',
    'diagram1': './img/political_view/zapravdu_astrahan-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_astrahan-group_joining.svg',
    'er': './img/group_joining/er/zapravdu_astrahan-group_joining.svg',
    'ldpr': './img/group_joining/ldpr/zapravdu_astrahan-group_joining.svg',
    'kprf': './img/group_joining/er/zapravdu_astrahan-group_joining.svg'
}, {
    'title': 'zapravdu_belgorodobl',
    'href': 'https://vk.com/zapravdu_belgorodobl',
    'diagram1': './img/political_view/zapravdu_belgorodobl-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_belgorodobl-group_joining.svg'
}, {
    'title': 'zapravdu_belgorod',
    'href': 'https://vk.com/zapravdu_belgorod',
    'diagram1': './img/political_view/zapravdu_belgorod-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_belgorod-group_joining.svg'
}, {
    'title': 'zapravdu_bryansk',
    'href': 'https://vk.com/zapravdu_bryansk',
    'diagram1': './img/political_view/zapravdu_bryansk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_bryansk-group_joining.svg'
}, {
    'title': 'zapravdubr',
    'href': 'https://vk.com/zapravdubr',
    'diagram1': './img/political_view/zapravdubr-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdubr-group_joining.svg'
}, {
    'title': 'zapravdubryansk',
    'href': 'https://vk.com/zapravdubryansk',
    'diagram1': './img/political_view/zapravdubryansk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdubryansk-group_joining.svg'
}, {
    'title': 'zapravdu_vladimir',
    'href': 'https://vk.com/zapravdu_vladimir',
    'diagram1': './img/political_view/zapravdu_vladimir-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_vladimir-group_joining.svg'
}, {
    'title': 'zapravdu_volgograd',
    'href': 'https://vk.com/zapravdu_volgograd',
    'diagram1': './img/political_view/zapravdu_volgograd-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_volgograd-group_joining.svg'
}, {
    'title': 'zapravdu_vologda',
    'href': 'https://vk.com/zapravdu_vologda',
    'diagram1': './img/political_view/zapravdu_vologda-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_vologda-group_joining.svg'
}, {
    'title': 'zapravdu_vrn',
    'href': 'https://vk.com/zapravdu_vrn',
    'diagram1': './img/political_view/zapravdu_vrn-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_vrn-group_joining.svg'
}, {
    'title': 'zapravdu_voronezh',
    'href': 'https://vk.com/zapravdu_voronezh',
    'diagram1': './img/political_view/zapravdu_voronezh-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_voronezh-group_joining.svg'
}, {
    'title': 'zapravdu_birobidzhan',
    'href': 'https://vk.com/zapravdu_birobidzhan',
    'diagram1': './img/political_view/zapravdu_birobidzhan-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_birobidzhan-group_joining.svg'
}, {
    'title': 'zapravdu_chita',
    'href': 'https://vk.com/zapravdu_chita',
    'diagram1': './img/political_view/zapravdu_chita-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_chita-group_joining.svg'
}, {
    'title': 'zapravdu_zabaikalie',
    'href': 'https://vk.com/zapravdu_zabaikalie',
    'diagram1': './img/political_view/zapravdu_zabaikalie-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_zabaikalie-group_joining.svg'
}, {
    'title': 'zapravdu_ivanovo',
    'href': 'https://vk.com/zapravdu_ivanovo',
    'diagram1': './img/political_view/zapravdu_ivanovo-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_ivanovo-group_joining.svg'
}, {
    'title': 'zapravdu_irkutsk',
    'href': 'https://vk.com/zapravdu_irkutsk',
    'diagram1': './img/political_view/zapravdu_irkutsk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_irkutsk-group_joining.svg'
}, {
    'title': 'zapravdu_kaliningrad',
    'href': 'https://vk.com/zapravdu_kaliningrad',
    'diagram1': './img/political_view/zapravdu_kaliningrad-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_kaliningrad-group_joining.svg'
}, {
    'title': 'zapravdukld',
    'href': 'https://vk.com/zapravdukld',
    'diagram1': './img/political_view/zapravdukld-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdukld-group_joining.svg'
}, {
    'title': 'zapravdu_kaluga',
    'href': 'https://vk.com/zapravdu_kaluga',
    'diagram1': './img/political_view/zapravdu_kaluga-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_kaluga-group_joining.svg'
}, {
    'title': 'zapravdu_kuzbass',
    'href': 'https://vk.com/zapravdu_kuzbass',
    'diagram1': './img/political_view/zapravdu_kuzbass-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_kuzbass-group_joining.svg'
}, {
    'title': 'zapravdu_kirov',
    'href': 'https://vk.com/zapravdu_kirov',
    'diagram1': './img/political_view/zapravdu_kirov-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_kirov-group_joining.svg'
}, {
    'title': 'zapravdu_kostromobl',
    'href': 'https://vk.com/zapravdu_kostromobl',
    'diagram1': './img/political_view/zapravdu_kostromobl-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_kostromobl-group_joining.svg'
}, {
    'title': 'zapravdu_kostroma',
    'href': 'https://vk.com/zapravdu_kostroma',
    'diagram1': './img/political_view/zapravdu_kostroma-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_kostroma-group_joining.svg'
}, {
    'title': 'zapravdu_krasnodar',
    'href': 'https://vk.com/zapravdu_krasnodar',
    'diagram1': './img/political_view/zapravdu_krasnodar-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_krasnodar-group_joining.svg'
}, {
    'title': 'zapravdu_krasnoyarsk',
    'href': 'https://vk.com/zapravdu_krasnoyarsk',
    'diagram1': './img/political_view/zapravdu_krasnoyarsk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_krasnoyarsk-group_joining.svg'
}, {
    'title': 'zapravdu_kansk',
    'href': 'https://vk.com/zapravdu_kansk',
    'diagram1': './img/political_view/zapravdu_kansk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_kansk-group_joining.svg'
}, {
    'title': 'zapravdu_kurgan',
    'href': 'https://vk.com/zapravdu_kurgan',
    'diagram1': './img/political_view/zapravdu_kurgan-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_kurgan-group_joining.svg'
}, {
    'title': 'zapravdukurgan',
    'href': 'https://vk.com/zapravdukurgan',
    'diagram1': './img/political_view/zapravdukurgan-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdukurgan-group_joining.svg'
}, {
    'title': 'zapravdu_kursk',
    'href': 'https://vk.com/zapravdu_kursk',
    'diagram1': './img/political_view/zapravdu_kursk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_kursk-group_joining.svg'
}, {
    'title': 'zapravdukursk',
    'href': 'https://vk.com/zapravdukursk',
    'diagram1': './img/political_view/zapravdukursk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdukursk-group_joining.svg'
}, {
    'title': 'zapravdu_lenoblast',
    'href': 'https://vk.com/zapravdu_lenoblast',
    'diagram1': './img/political_view/zapravdu_lenoblast-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_lenoblast-group_joining.svg'
}, {
    'title': 'zapravdulenobl',
    'href': 'https://vk.com/zapravdulenobl',
    'diagram1': './img/political_view/zapravdulenobl-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdulenobl-group_joining.svg'
}, {
    'title': 'zapravdu_lipeck',
    'href': 'https://vk.com/zapravdu_lipeck',
    'diagram1': './img/political_view/zapravdu_lipeck-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_lipeck-group_joining.svg'
}, {
    'title': 'zapravdu_magadanobl',
    'href': 'https://vk.com/zapravdu_magadanobl',
    'diagram1': './img/political_view/zapravdu_magadanobl-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_magadanobl-group_joining.svg'
}, {
    'title': 'zapravdu_msk',
    'href': 'https://vk.com/zapravdu_msk',
    'diagram1': './img/political_view/zapravdu_msk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_msk-group_joining.svg'
}, {
    'title': 'zapravdukhimki',
    'href': 'https://vk.com/zapravdukhimki',
    'diagram1': './img/political_view/zapravdukhimki-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdukhimki-group_joining.svg'
}, {
    'title': 'zapravdu_mosobl',
    'href': 'https://vk.com/zapravdu_mosobl',
    'diagram1': './img/political_view/zapravdu_mosobl-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_mosobl-group_joining.svg'
}, {
    'title': 'zapravdubalaxna',
    'href': 'https://vk.com/zapravdubalaxna',
    'diagram1': './img/political_view/zapravdubalaxna-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdubalaxna-group_joining.svg'
}, {
    'title': 'zapravduvn',
    'href': 'https://vk.com/zapravduvn',
    'diagram1': './img/political_view/zapravduvn-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravduvn-group_joining.svg'
}, {
    'title': 'zapravdu_novosibirsk',
    'href': 'https://vk.com/zapravdu_novosibirsk',
    'diagram1': './img/political_view/zapravdu_novosibirsk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_novosibirsk-group_joining.svg'
}, {
    'title': 'zapravdu_omsk',
    'href': 'https://vk.com/zapravdu_omsk',
    'diagram1': './img/political_view/zapravdu_omsk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_omsk-group_joining.svg'
}, {
    'title': 'zapravduomsk',
    'href': 'https://vk.com/zapravduomsk',
    'diagram1': './img/political_view/zapravduomsk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravduomsk-group_joining.svg'
}, {
    'title': 'zapravdu_orenburg',
    'href': 'https://vk.com/zapravdu_orenburg',
    'diagram1': './img/political_view/zapravdu_orenburg-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_orenburg-group_joining.svg'
}, {
    'title': 'zapravdu_oryol',
    'href': 'https://vk.com/zapravdu_oryol',
    'diagram1': './img/political_view/zapravdu_oryol-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_oryol-group_joining.svg'
}, {
    'title': 'zapravdu_penza',
    'href': 'https://vk.com/zapravdu_penza',
    'diagram1': './img/political_view/zapravdu_penza-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_penza-group_joining.svg'
}, {
    'title': 'zapravdu_perm',
    'href': 'https://vk.com/zapravdu_perm',
    'diagram1': './img/political_view/zapravdu_perm-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_perm-group_joining.svg'
}, {
    'title': 'zapravdu_vladivostok',
    'href': 'https://vk.com/zapravdu_vladivostok',
    'diagram1': './img/political_view/zapravdu_vladivostok-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_vladivostok-group_joining.svg'
}, {
    'title': 'vk.comzapravdupskov',
    'href': 'https://vk.com/vk.comzapravdupskov',
    'diagram1': './img/political_view/vk.comzapravdupskov-political_view.svg',
    'navalny': './img/group_joining/navalny/vk.comzapravdupskov-group_joining.svg'
}, {
    'title': 'zapravdu_ufa',
    'href': 'https://vk.com/zapravdu_ufa',
    'diagram1': './img/political_view/zapravdu_ufa-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_ufa-group_joining.svg'
}, {
    'title': 'zapravdu_ufarb',
    'href': 'https://vk.com/zapravdu_ufarb',
    'diagram1': './img/political_view/zapravdu_ufarb-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_ufarb-group_joining.svg'
}, {
    'title': 'zapravdu_krym',
    'href': 'https://vk.com/zapravdu_krym',
    'diagram1': './img/political_view/zapravdu_krym-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_krym-group_joining.svg'
}, {
    'title': 'zapravdu_alania',
    'href': 'https://vk.com/zapravdu_alania',
    'diagram1': './img/political_view/zapravdu_alania-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_alania-group_joining.svg'
}, {
    'title': 'zapravdu_kazan',
    'href': 'https://vk.com/zapravdu_kazan',
    'diagram1': './img/political_view/zapravdu_kazan-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_kazan-group_joining.svg'
}, {
    'title': 'zapravdu_rov',
    'href': 'https://vk.com/zapravdu_rov',
    'diagram1': './img/political_view/zapravdu_rov-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_rov-group_joining.svg'
}, {
    'title': 'zapravdu_ryazan',
    'href': 'https://vk.com/zapravdu_ryazan',
    'diagram1': './img/political_view/zapravdu_ryazan-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_ryazan-group_joining.svg'
}, {
    'title': 'zapravdu_samara',
    'href': 'https://vk.com/zapravdu_samara',
    'diagram1': './img/political_view/zapravdu_samara-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_samara-group_joining.svg'
}, {
    'title': 'zapravdu_spb',
    'href': 'https://vk.com/zapravdu_spb',
    'diagram1': './img/political_view/zapravdu_spb-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_spb-group_joining.svg'
}, {
    'title': 'zapravdu_saratov',
    'href': 'https://vk.com/zapravdu_saratov',
    'diagram1': './img/political_view/zapravdu_saratov-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_saratov-group_joining.svg'
}, {
    'title': 'zapravdu_ekb',
    'href': 'https://vk.com/zapravdu_ekb',
    'diagram1': './img/political_view/zapravdu_ekb-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_ekb-group_joining.svg'
}, {
    'title': 'zapravdu_v_sevastopol',
    'href': 'https://vk.com/zapravdu_v_sevastopol',
    'diagram1': './img/political_view/zapravdu_v_sevastopol-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_v_sevastopol-group_joining.svg'
}, {
    'title': 'zapravdu_stavropol',
    'href': 'https://vk.com/zapravdu_stavropol',
    'diagram1': './img/political_view/zapravdu_stavropol-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_stavropol-group_joining.svg'
}, {
    'title': 'zapravdu_tambov',
    'href': 'https://vk.com/zapravdu_tambov',
    'diagram1': './img/political_view/zapravdu_tambov-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_tambov-group_joining.svg'
}, {
    'title': 'zapravdu_tver',
    'href': 'https://vk.com/zapravdu_tver',
    'diagram1': './img/political_view/zapravdu_tver-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_tver-group_joining.svg'
}, {
    'title': 'zapravdutv',
    'href': 'https://vk.com/zapravdutv',
    'diagram1': './img/political_view/zapravdutv-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdutv-group_joining.svg'
}, {
    'title': 'zapravdu_tomsk',
    'href': 'https://vk.com/zapravdu_tomsk',
    'diagram1': './img/political_view/zapravdu_tomsk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_tomsk-group_joining.svg'
}, {
    'title': 'zapravdu_ulianovsk',
    'href': 'https://vk.com/zapravdu_ulianovsk',
    'diagram1': './img/political_view/zapravdu_ulianovsk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_ulianovsk-group_joining.svg'
}, {
    'title': 'club33296839',
    'href': 'https://vk.com/club33296839',
    'diagram1': './img/political_view/club33296839-political_view.svg',
    'navalny': './img/group_joining/navalny/club33296839-group_joining.svg'
}, {
    'title': 'zapravdu_habarovsk',
    'href': 'https://vk.com/zapravdu_habarovsk',
    'diagram1': './img/political_view/zapravdu_habarovsk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_habarovsk-group_joining.svg'
}, {
    'title': 'zapravdu_chelyabinsk',
    'href': 'https://vk.com/zapravdu_chelyabinsk',
    'diagram1': './img/political_view/zapravdu_chelyabinsk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_chelyabinsk-group_joining.svg'
}, {
    'title': 'zapravdu_magnitogorsk',
    'href': 'https://vk.com/zapravdu_magnitogorsk',
    'diagram1': './img/political_view/zapravdu_magnitogorsk-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_magnitogorsk-group_joining.svg'
}, {
    'title': 'zlatoustzapravdu',
    'href': 'https://vk.com/zlatoustzapravdu',
    'diagram1': './img/political_view/zlatoustzapravdu-political_view.svg',
    'navalny': './img/group_joining/navalny/zlatoustzapravdu-group_joining.svg'
}, {
    'title': 'zapravdu_chuv',
    'href': 'https://vk.com/zapravdu_chuv',
    'diagram1': './img/political_view/zapravdu_chuv-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_chuv-group_joining.svg'
}, {
    'title': 'zapravdu89',
    'href': 'https://vk.com/zapravdu89',
    'diagram1': './img/political_view/zapravdu89-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu89-group_joining.svg'
}, {
    'title': 'zapravdu_yaroslavl',
    'href': 'https://vk.com/zapravdu_yaroslavl',
    'diagram1': './img/political_view/zapravdu_yaroslavl-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_yaroslavl-group_joining.svg'
}, {
    'title': 'zapravdu_dnr',
    'href': 'https://vk.com/zapravdu_dnr',
    'diagram1': './img/political_view/zapravdu_dnr-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_dnr-group_joining.svg'
}, {
    'title': 'zapravdu_amur',
    'href': 'https://m.vk.com/zapravdu_amur',
    'diagram1': './img/political_view/zapravdu_amur-political_view.svg',
    'navalny': './img/group_joining/navalny/zapravdu_amur-group_joining.svg'
}, ]


let NewArr = []


arr.forEach(el => {
    let a = el.navalny.split('/')[4]
    NewArr.push({
        'title': el.title,
        'href': el.href,
        'diagram1': el.diagram1,
        'navalny': el.navalny,
        'er' : `/img/group_joining/er/${a}`,
        'ldpr' : `/img/group_joining/ldpr/${a}`, 
        'kprf' : `/img/group_joining/kprf/${a}`
    })
})


console.log(NewArr);